### ISSUE TITLE
Works on Windows Subsystem for Linux (WSL) too

### ISSUE THREAD

**Issue by danmindru** [ryochack/peep#1]
Hi there,

Thanks for the nice lib. Got to try it on WSL & it seems to work fine.

| hyper | Bash |
|--------|------|
|     ![peep1](https://user-images.githubusercontent.com/1515742/51259791-273f3080-19ad-11e9-92f1-884044064100.PNG) |      ![peep2](https://user-images.githubusercontent.com/1515742/51259872-4fc72a80-19ad-11e9-9d41-464713758087.PNG) |

In case someone else is wondering...

Cheers,
Dan

**Comment by ryochack** [comment]
Hi @danmindru ,

Thanks for your report.
I'm pleased that you are using peep.

I couldn't try running peep on WSL, because I don't have Windows.
So, your information will be useful to Windows users;)

**Comment by sergeevabc** [comment]
> So, your information will be useful to Windows users;)

For Windows _10 users_, what about Windows 7? If anyone skilled with building binaries stumbles upon this thread, please try.
