### ISSUE TITLE
Support moving with arrows, PageUp, PageDown, …

### ISSUE THREAD

**Issue by jirutka** [ryochack/peep#11]
Could you please consider adding the following alternative key bindings?

```
DownArrow   Scroll down
UpArrow     Scroll up
PageDown    Scroll down a page
PageUp      Scroll up a page
RightArrow  Scroll horizontally right
LeftArrow   Scroll horizontally left
Home        Go to the beggining of line
End         Go to the end of line
```

**Comment by ryochack** [comment]
@jirutka I'm sorry for late reply.
peep supports these key bindings at https://github.com/ryochack/peep/commit/514ab0f1bf9d3a5c03df3ea88388c64c4c7308a7 (on the develop branch).

Please try it if you would like.

**Comment by jirutka** [comment]
It works perfectly, thanks!

**Comment by ryochack** [comment]
Thanks for reporting!
