### ISSUE TITLE
Homebrewでインストールできるようにしませんか？

### ISSUE THREAD

**Issue by golddranks** [ryochack/peep#2]
Homebrewでインストールできたらいいなと思ったりしますが、いかがでしょうか？パッケージ作るのはそんな大きなハードルではないはずですし、よかったら作ってあげます。

**Comment by ryochack** [comment]
ご提案ありがとうございます！
私は普段Macを使っていないのですが、Homebrewからpeepをインストールできるようになったらとても嬉しいです。
是非お願いしたいです。

**Comment by golddranks** [comment]
https://github.com/Homebrew/homebrew-core/pull/41046 HomebrewにPR送りました！
