### ISSUE TITLE
Feature: Support clearing peep output on exit

### ISSUE THREAD

**Issue by b0o** [ryochack/peep#8]
By default, when less exits, the text it was displaying is cleared and the user's terminal window is returned to the state it was in prior to less being invoked. 

I think this is a vital feature of less, and of short-lived interactive CLI utilities in general (programs like [fzf](https://github.com/junegunn/fzf), [bat](https://github.com/sharkdp/bat), etc. also implement this feature). 

Peep's selling point seems to be its focus on not displacing the surrounding terminal context; I think that the functionality I just described would be very complementary to this focus.

As a workaround, I wrote a little wrapper script which basically accomplishes this (requires ncurses):

```sh
#!/bin/bash
set -euo pipefail

function isset_help() {
  local opt
  for opt in "$@"; do
    case "$opt" in
      --)
        echo 0
        return 0
        ;;
      --help)
        echo 1
        return 0
        ;;
    esac
  done

  while getopts ':h' opt "$@"; do
    case "$opt" in
      h)
        echo 1
        return 0
        ;;
      *)
        continue
        ;;
    esac
  done

  echo 0
  return 0
}

function main() {
  local -i h
  h=$(isset_help "$@")
  [[ $h -eq 0 ]] && tput sc
  peep "$@"
  local -i c=$?
  [[ $c -eq 0 && $h -eq 0 ]] && tput rc
  return $c
}

main "$@"
```

Before:

https://user-images.githubusercontent.com/21299126/104421767-a6ca5080-5530-11eb-9787-2d38ec2bd9a0.mp4

After:

https://user-images.githubusercontent.com/21299126/104421790-adf15e80-5530-11eb-8da3-016f47d36ba1.mp4

It's far from ideal and doesn't work when the cursor line is at or within `--lines` of the bottom of the terminal window, but it should give you an idea of what I am proposing.

Thanks for creating this project, I really love using it!

**Comment by ryochack** [comment]
Hi, @b0o
Thank you for your suggestion and I'm very sorry that the reply is very late.

It is peep's specification to leave the output text on exit.
This is intended to work like the cat, head, or tail commands.

However, I think your suggestion is very useful.
So, I added the 'Q' command to quit after clearing the output text. ( https://github.com/ryochack/peep/commit/95ec1e16f23b0be36620daf031a2e274be17af0f )

I hope this command will help you.

**Comment by b0o** [comment]
I just tested this change, it works perfectly. Thank you!
